In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
illness=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/mental-illnesses-prevalence.csv')
illness

Entity Code  Year  sleep hour  work stress  screen time  \
0     Afghanistan  AFG  1990           5            5            1   
1     Afghanistan  AFG  1991           5            5            1   
2     Afghanistan  AFG  1992           5            5            1   
3     Afghanistan  AFG  1993           5            5            1   
4     Afghanistan  AFG  1994           5            5            1   
...           ...  ...   ...         ...          ...          ...   
6415     Zimbabwe  ZWE  2015           3            3            1   
6416     Zimbabwe  ZWE  2016           3            3            1   
6417     Zimbabwe  ZWE  2017           3            3            1   
6418     Zimbabwe  ZWE  2018           3            3            1   
6419     Zimbabwe  ZWE  2019           3            3            1   

      social interaction  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  
...                  ...  
6415                   0  
6416                   0  
6417                   0  
6418                   0  
6419                   0  

[6420 rows x 7 columns]

In [5]:
illness.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6420 entries, 0 to 6419
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Entity              6420 non-null   object
 1   Code                6150 non-null   object
 2   Year                6420 non-null   int64 
 3   sleep hour          6420 non-null   int64 
 4   work stress         6420 non-null   int64 
 5   screen time         6420 non-null   int64 
 6   social interaction  6420 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 351.2+ KB


In [6]:
illness.shape

(6420, 7)

In [7]:
illness.size

44940

In [8]:
illness.ndim

2

In [9]:
illness.columns

Index(['Entity', 'Code', 'Year', 'sleep hour', 'work stress', 'screen time',
       'social interaction'],
      dtype='object')

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [11]:
x = illness[['sleep hour']]
y = illness['work stress']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
imputer = SimpleImputer(strategy='mean')
x_train = imputer.fit_transform(x_train)
model= LogisticRegression(solver='liblinear', random_state=0)
model.fit(x_train,y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [15]:
predictions = model.predict(x_test)
predictions

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([4, 4, 4, ..., 4, 4, 4])

In [14]:
y_pred = model.predict(x_test)
y_pred

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([4, 4, 4, ..., 4, 4, 4])

In [16]:
new = [[5]]
y_pred_test = model.predict(new)
y_pred_test

array([4])

In [23]:
threshold = 8;

In [24]:
illness= y_pred.mean()
illness
if illness>=threshold:
  print("risk")
else:
  print("not risk")

not risk
